version: "3.1"
services:
  server:
    build:
      context: ${SERVER_ROOT}/bin/${PHP_VERSION}
    container_name: ${PHP_VERSION}
    restart: 'always'
    # links:
    #   - database
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      # - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes:
      - ${PROJECT_ROOT}:/var/www/html/
      - ${SERVER_ROOT}${PHP_INI}:/usr/local/etc/php/php.ini
      - ${SERVER_ROOT}${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${SERVER_ROOT}${APACHE_LOG_DIR}:/var/log/apache2
    environment:
      ENV: dev
  # database:
  #   build:
  #     context: "${SERVER_ROOT}/bin/${MYSQL_VERSION}"
  #   container_name: ${MYSQL_VERSION}
  #   restart: 'always'
  #   ports:
  #     - "${HOST_MACHINE_MYSQL_PORT}:3306"
  #   volumes:
  #     - ${SERVER_ROOT}${MYSQL_DATA_DIR}:/var/lib/mysql
  #     - ${SERVER_ROOT}${MYSQL_LOG_DIR}:/var/log/mysql
    # phpmyadmin:
    #   image: phpmyadmin/phpmyadmin
    #   container_name: 'phpmyadmin'
    #   links:
    #     - database
    #   ports:
    #     - "${HOST_MACHINE_PHPMYADMIN_PORT}:80"
    # volumes:
    #   - /sessions
    #   - ${SERVER_ROOT}${PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini